server:
  port: 8085
  servlet:
    context-path: /oraclecloud
spring:
  application:
    name: oraclecloud
  datasource:
    url: jdbc:oracle:thin:@atpprueba0001_medium?TNS_ADMIN=D:/Wallets/aptprueba0001
    username: workshop
    password: Vallegrande#2023
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    show-sql: true

oracle:
  jdbc:
    fanEnabled: false